name: netAnalysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "5.0"  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with nullable checks
        run:
          dotnet build --configuration Release --no-restore
          /p:Nullable=annotations /p:TreatWarningsAsErrors=false 
          /nowarn:CS8600,CS8602,CS8603,CS8604,CS8618,CS8625

      - name: Run tests
        run: dotnet test --no-build --verbosity normal