on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "5.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with warnings as errors
        run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=true

      - name: Run tests
        run: dotnet test --no-build --verbosity normal