name: deploy_docker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  dotnet-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "5.0"
      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore /nowarn:CS8618,CS8625
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  docker-build:
    runs-on: ubuntu-latest
    needs: dotnet-check
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Investing/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/investing:latest
